public interface ActivityDAInterface {
    //List<ActivityDA.ActivityCombined> getOpenActivitiesByContactId(Id contactId);
    //List<ActivityDA.ActivityCombined> getOpenActivitiesByOpportunityId(Id opportunityId);
    //List<ActivityDA.ActivityCombined> getOpenActivitiesByLeadId(Id leadId);
    //List<ActivityDA.ActivityCombined> getOpenActivitiesByAccountId(Id accountId);
    //List<ActivityDA.ActivityCombined> getOpenActivitiesByReferralContactId(Id referralContactId);    
    //List<ActivityDA.ActivityCombined> getOpenActivitiesByReferralAccountId(Id referralAccountId);    
    //List<Event> getInitialPresentationEventsByOpportunityId(Id opportunityId);
    //List<Event> getEventsByRelatedId(Id leadId);
    //List<Task> getTasksByRelatedId(Id leadId);
    //List<OpportunityContactRole> getContactRolesByOpportunityId(Id opportunityId); 
}