public with sharing class CalendarDayOutput {
	
      // the displayed name
      public String userName{get;set;}
      // the date string used for the onClick
      public String dateStr{get;set;}
      
      public Boolean isBusy08am{get;set;}
      public Boolean isBusy09am{get;set;}
      public Boolean isBusy10am{get;set;}
      public Boolean isBusy11am{get;set;}
      public Boolean isBusy12pm{get;set;}
      public Boolean isBusy01pm{get;set;}
      public Boolean isBusy02pm{get;set;}
      public Boolean isBusy03pm{get;set;}
      public Boolean isBusy04pm{get;set;}
      public Boolean isBusy05pm{get;set;}
      public Boolean isBusy06pm{get;set;}
      
} // class CalendarDayOutput