/* 
 * The test methods for the NSSZipBatch class.
 *
 * History
 * -------
 * 02/03/2010 Dan Carmen   Created
 * 07/12/2010 Dan Carmen   Added checks for reaching limits.
   07/11/2011 Dan Carmen   Modify process to update all ownership fields at once.
   10/26/2018 Dan Carmen   Increment API to version 44

 */
@isTest
private class NSSZipBatchTest {

   static testMethod void testNothing() {
      NSSZipBatch nzb = new NSSZipBatch();
   }
   
} // class NSSZipBatchTest